#!/bin/bash

# Quickly open public PORT on IP via assigned ROUTE#
help()
{
    echo "Set parameters before use"
    echo "Example: ./$0 run <Guest VM IP> <port>"
}
run()
{
    # Parameters
    ROUTE="virbr0"
    sudo iptables -t nat -I PREROUTING -p tcp --dport $2 -j DNAT --to $1:$2
    echo "EXECUTED"
}

if [[ $1 == 'run' ]]
then
    run $2 $3
elif [[ $1 == '-h' || $# -eq 0 ]]
then
    help
else
    exit 1
fi

